add client model, employee model, js mask and css style
ALFA-E-OMEGA/super-duper-winner pull request #1
Opened 2024-02-08 22:31 UTC by itallovidal

problem with js mask loading

2024-02-12 16:47 UTC, J4g3rWulf approved these changes

2024-02-16 19:59 UTC, giovannism20 requested changes

2024-02-16 19:59 UTC, giovannism20 commented on registers/static/static/description/icon.png
Por que precisamos dessa imagem ? Estamos utilizando em algum trecho ?

2024-02-16 19:59 UTC, giovannism20 commented on registers/static/static/description/main_screenshot.png
Por que precisamos dessa imagem ? Estamos utilizando em algum trecho ?

2024-02-16 19:59 UTC, giovannism20 commented on registers/views/menu.xml
> +                sequence="10"/> -->
Acredito que podemos remover esse trecho se não estamos utilizando

2024-02-16 19:59 UTC, giovannism20 commented on registers/static/static/src/xml/mask.xml
> +          <!--contenteditable="false"/>-->
Acredito que podemos remover esse trecho se não estamos utilizando

2024-02-16 19:59 UTC, giovannism20 commented on registers/static/static/lib/jquery.inputmask/jquery.inputmask.bundle.js
O que faz esse arquivo ? Realmente utilizamos ele ?

2024-02-19 23:30 UTC, giovannism20 requested changes

2024-02-19 23:30 UTC, giovannism20 commented on registers/static/src/js/createEmployee.js
> +    // }, 1000)
Bastante código deletado, podemos remover, não ?

2024-02-19 23:30 UTC, giovannism20 commented on registers/models/__pycache__/__init__.cpython-310.pyc
O que é essa modificação ?

2024-02-19 23:30 UTC, giovannism20 commented on registers/models/__pycache__/client.cpython-310.pyc
O que é essa modificação ?

2024-02-19 23:30 UTC, giovannism20 commented on registers/models/__pycache__/employee.cpython-310.pyc
O que é essa modificação ?

2024-02-19 23:30 UTC, giovannism20 commented on registers/__manifest__.py
> +        # 'security/ir.model.access.csv',
Código comentado podemos remover, né ?

2024-02-19 23:30 UTC, giovannism20 commented on registers/models/__init__.py
> +from . import patrimony
O que faz esse import ?

2024-02-19 23:34 UTC, itallovidal commented on registers/static/src/js/createEmployee.js
> +    // }, 1000)
esse código não está deletado, está comentado apenas pois está com aquele problema ao carregar. Esse arquivo ele carrega assim que o módulo é carregado, então ele procura os inputs para mascarar e não encontra. Neste caso, teria que fazer com que ou o js carregasse apenas na página correta, ou fazer com que ele só disparasse a máscara quando o input existe. Para não dar erro ou comentei

2024-02-19 23:36 UTC, itallovidal commented on registers/models/__pycache__/client.cpython-310.pyc
esses três arquivos são os arquivos temporários gerados pelos init, acredito. Eu já criei um gitignore para ignorar esses arquivos d o__pycache__

2024-02-20 00:34 UTC, giovannism20 commented on registers/models/__pycache__/client.cpython-310.pyc
Beleza. Pode deletar então que nas próximas vezes se ele criar local não vai subir  para o Github.

2024-02-20 00:35 UTC, giovannism20 commented on registers/static/src/js/createEmployee.js
> +    // }, 1000)
Faz sentido deixar comentado ou podemos deletar então ?

2024-02-20 21:54 UTC, giovannism20 approved these changes

2024-02-20 21:55 UTC, merged